### ISSUE TITLE
Comments + Formulas

### ISSUE THREAD

**Issue by franzpl** [Pravinnarola/NFC#4]
Well done! 

I have just a few issues: 

- don't forget to comment (nobody knows what p, q , etc. is..)
- you can use comments for units as well (example: f = 13.56 # MHz) 
- above your code, you can use latex formulas in markdown cells like in this example : https://github.com/franzpl/StableGrid/blob/master/jupyter_notebooks/computation_schmitt_trigger.ipynb
--> it will improve the readability

**Comment by JakobHeller** [comment]
Looks nice, but there are some problems left:
* f=13.56*10**6 (as you use MHz)
* y=a0*e**(-alpha*z) (alpha should not be complex, the rotation is in the e**(..) not in the alpha)
* since you already use numpy you should use np.sqrt() not (...)**(1/2) it is not good for the readability
* for pi and e i mostly use numpy.pi and math.e (just a recommendation)
* The attenuation is not in db, it uses gradations from 1.0
* for the tile you could use Attenuation in lossy dielectrics (since you do not use skin alone)

For the Text:
* Grammar/Spelling
* maybe you could talk about the difference between passive and active readers
